---
- name: Ensure traefik directory
  file:
    path: "{{ traefik_dir }}"
    state: directory
    mode: '0755'

- name: Copy main traefik configuration
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_dir }}/traefik.yml"
    mode: '0755'

- name: Ensure traefik directory
  file:
    path: "{{ traefik_file_provider['filename'] | dirname }}"
    state: directory
    mode: '0755'
  when: '"filename" in traefik_file_provider'

- name: Ensure traefik log file
  file:
    path: "{{ traefik_logs['filePath'] }}"
    mode: '0755'
    state: touch
  when: '"filePath" in traefik_logs'

- name: Copy file provider configuration
  template:
    src: file-provider.yml.j2
    dest: "{{ traefik_file_provider['filename'] }}"
    mode: '0755'
  when: '"filename" in traefik_file_provider'

- name: Build traefik container compose configuration
  set_fact:
    docker_traefik_configuration: |
          image: {{ traefik_image }}
          container_name: {{ traefik_container_name }}
          restart: unless-stopped

          {% if traefik_host_network_mode_host -%}
          network_mode: host
          {% endif %}

          {% if traefic_commands | length > 0 %}
          command:
            {{ traefic_commands | to_yaml  | indent(6) }}
          {% endif %}

          {% if traefik_container_labels | length > 0 %}
          labels:
            {{ traefik_container_labels | to_yaml  | indent(6) }}
          {% endif %}

          {% if traefik_container_networks | length > 0 %}
          networks:
            {{ traefik_container_networks.keys() | list | to_yaml  | indent(6) }}
          {% endif %}

          volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - {{ traefik_dir }}:/etc/traefik
            {% if 'filePath' in traefik_logs -%}
            - {{ traefik_logs['filePath'] }}:{{ traefik_logs['filePath'] }}
            {% endif -%}

    docker_traefik_networks: |
          {% if traefik_container_networks | length > 0 %}
          {{ traefik_container_networks | to_yaml }}
          {% else %}
          {}
          {% endif %}

- name: Setup traefik
  docker_compose:
    state: present
    project_name: traefik
    definition:
      version: '3.5'
      services:
        traefik: "{{ docker_traefik_configuration | from_yaml }}"
      networks: "{{ docker_traefik_networks | from_yaml }}"
